---
- yum:
    name: "{{ item }}"
  with_items:
    - python-pip
    - python-devel
    - libffi-devel
    - git

- pip:
    name: "{{ item }}"
  with_items:
    - Unidecode==0.4.17
    - cryptography==0.6.1
    - httplib2.ca-certs-locater
    - python-ldap
    - netifaces
    - fuzzywuzzy
    - python-Levenshtein
    - python-cinderclient==1.0.9
    - python-glanceclient==0.13.1
    - python-keystoneclient==0.11.2
    - python-neutronclient==2.3.6
    - python-novaclient==2.20.0
    - python-swiftclient==2.3.1

- file:
    path: /usr/local/lib/
    mode: 0757

- git:
    repo: ssh://gitlab@git.forgeservicelab.fi:10022/forge/insightly-sync.git
    dest: /usr/local/lib/Insightly_LDAP
    accept_hostkey: yes
    ssh_opts: "-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
  sudo: false

- template:
    src: identity
    dest: /usr/local/lib/Insightly_LDAP/identity
    owner: root
    group: root
    mode: 0600

- cron:
    name: Poll Insightly for updates
    minute: '*/5'
    job: /usr/local/lib/Insightly_LDAP/ldapsync.py -r /usr/local/lib/Insightly_LDAP/identity >> /dev/null 2>&1
    user: "{{ cron_user }}"
